### ISSUE TITLE
Still broken

### ISSUE THREAD

**Issue by oerjan** [DatCodingGuy/Deadfish#1]
Nope, still broken. Note that part of the reason for Deadfish's popularity is that it's crazy and doesn't work the way one would think at first glance. I suggest trying the test programs, I have just modified them a bit to catch more gotchas.

**Comment by DatCodingGuy** [comment]
Aaah, I think I see it, is it the square command? If it goes over 256 it has to wrap, go back to 0 and continue?

**Comment by oerjan** [comment]
No, that is not right. s should only wrap when it hits 256 *exactly*. In fact all of i, d, and s have errors. I'm not sure about o since I don't know C#'s output system, but it *should* print a number rather than a character.

I suggest you try running another interpreter to compare tests with (the first C one is the most official).

**Comment by DatCodingGuy** [comment]
ah, I understand, so numbers should only wrap if they hit exactly 256? Is it the same as if they hit exactly -1? And I've currently got it so that it outputs a character but it's rather confusing because on the wiki it doesn't say anything about the output and since there's a Hello World program written for it I automatically assumed it outputs as a character.

**Comment by oerjan** [comment]
Yep! And good point on the Hello World program, I've added a clarification.

**Comment by oerjan** [comment]
Oh, and the other errors were: i tries to do the right thing but has a subtle off by one error, and d should wrap -1 to 0, not 256.

**Comment by DatCodingGuy** [comment]
what do you mean "off by one" error? I've fixed the wrapping issue, now it has a set function near the end of the loop that says "if cell == 0 or 256 then cell = 0", that should have fixed the d wrapping error.

**Comment by oerjan** [comment]
Looks good to me now! Previously the program checked in the i case for cell == 256 *before* incrementing instead of after.

**Comment by DatCodingGuy** [comment]
Yeah, that's because my initial logic was "if it's going to increment to above 256 then wrap to 0", before that (when you first told me there was a big) the logic was set to "if it's going to increment _to_ 256 then it wraps to 0". My first logic would've been fine but it didn't account for squaring the number and my new bit of code is more efficient too. Am I able to put it back on the wiki?

**Comment by oerjan** [comment]
Sure :)

**Comment by DatCodingGuy** [comment]
I also fixed my Fishstacks interpreter, after this whole Deadfish thing I realized that was broken too :P
